name: lint

on:
  push:
    branches: [ "main" ]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Installing Rust toolchain
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: stable
        targets: x86_64-unknown-linux-gnu
    - name: Format
      run: cargo fmt --check
    - name: Clippy
      run: cargo clippy -- -Dwarnings
